name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  title:
    name: ticket check
    runs-on: ubuntu-latest

    steps:
      - name: Pull Request Ticket Check Action
        uses: neofinancial/ticket-check-action@v1.3.2
        with:
          token: ${{ secrets.PULL_REQUEST_TOKEN }}
          ticketPrefix: '#'
          titleRegex: '^#(\d+)'
          branchRegex: '^(\d+)'
          bodyRegex: '#(\d+)'
          bodyURLRegex: 'http(s?):\/\/(github.com)(\/:owner)(\/:repo)(\/issues)\/\d+'
